#! /bin/sh

/bin/echo -e "/*This file is auto-generated by the build system!*/\n#include \"mattak/Version.h\"\n\nconst char *  mattak::version() { return \"$(git describe --always --dirty --match 'NOT A TAG')\";}" > $1/Version.cc ;
