#! /bin/sh

/bin/echo -e "/*This file is auto-generated by the build system!*/\n#include \"mattak/Version.h\"\n\nconst char *  mattak::version() { return \"$(git describe --always --dirty --match 'NOT A TAG')\";}" > $1/Version.cc.tmp ;
if diff -q $1/Version.cc.tmp $1/Version.cc  >/dev/null 2>&1;
then
  rm $1/Version.cc; else mv $1/Version.cc.tmp $1/Version.cc ;
fi
