#! /bin/bash

# don't expand globs to themselves if no match
shopt -s nullglob

INDIR=${1-.}
OUTDIR=${2-$INDIR/root}
FORCE=${3-0}
STATION_OVERRIDE=${4--1}
RUN_OVERRIDE=${5--1}

if [[ -z "${RNO_G_INSTALL_DIR}" ]]; then
  echo "RNO_G_INSTALL_DIR is not set. Can not locate mon_write.py, please set. Exit.."
  exit 1
fi
SCRIPT_DIR="${RNO_G_INSTALL_DIR}/bin"

if [ "${INDIR}" = "${OUTDIR}" ];
then
  echo "Cannot put ROOT files into input directory"
  exit 1
fi

echo "input directory is ${INDIR}"
echo "output directory is ${OUTDIR}"

# Only check if (any) waveform file(s) are already copied as the later conversion
# (with no-g-convert wf) fails if no waveform file is present (regardless of whether
# a e.g. header file is already copied).
wf_files=("${INDIR}"/waveforms/*)
if [ ${#wf_files[@]} -eq 0 ]; then
  echo "No waveform files in ${INDIR}/waveforms yet, nothing to convert"
  exit 0
fi

NEED_TO_UPDATE=1

# This checks whether an existing, and maybe only partially converted run, needs to be updated
if [ ${FORCE} -eq 0 ]
then
  if  [ -f "${OUTDIR}/rootified-list.txt" ] && [ -f "${OUTDIR}/aux/acq-file-list.txt" ]  ;
  then
    diff "${INDIR}/aux/acq-file-list.txt" "${OUTDIR}/aux/acq-file-list.txt"  && \
      diff  "${OUTDIR}/rootified-list.txt" <( find "${INDIR}" | sort )
    NEED_TO_UPDATE=$?
    echo "output directory found, need to update = $NEED_TO_UPDATE"
  fi;
fi

mkdir -p "${OUTDIR}"

if [ ${NEED_TO_UPDATE} -eq 1 ] ; then

  # Create a temporary file and clean up at EXIT
  tmpfile=$(mktemp)
  trap 'rm -f "$tmpfile"' EXIT

  # Look for the voltage calibration file already
  # existing in the output directory
  calibration_file=("${OUTDIR}"/volCalConsts*)

  if [ ! -f "${INDIR}/aux/runinfo.txt" ]; then
    echo "Did not find runinfo.txt for input dir ${INDIR}. Exit..."
    exit 1;
  fi

  # Check if we are DiDAQ
  grep -iq didaq ~/station25/run26064/aux/runinfo.txt
  ON_DIDAQ=$(( !$? ))

  echo "Making rootified list" \
    && find "${INDIR}" | sort -o "$tmpfile" \
    && echo "Converting waveforms"  \
    && rno-g-convert wf "${OUTDIR}/waveforms.root" "${INDIR}"/waveforms/* \
    && echo "Converting headers"  \
    && rno-g-convert hd "${OUTDIR}/headers.root" "${INDIR}"/header/* \
    && echo "Converting daqstatus" \
    && rno-g-convert ds "${OUTDIR}/daqstatus.root" "${INDIR}"/daqstatus/* \
    && { [ $ON_DIDAQ -eq 0 ] && echo "Converting pedestals" \
    && rno-g-convert ped "${OUTDIR}/pedestal.root" "${INDIR}"/pedestals.dat* \
    || true; } \
    && echo "Converting runinfo" \
    && rno-g-convert runinfo "${OUTDIR}/runinfo.root" "${INDIR}/aux" "${STATION_OVERRIDE}" "${RUN_OVERRIDE}" \
    && echo "Copying aux and cfg"  \
    && cp -p -r "${INDIR}/aux"  "${OUTDIR}"/ \
    && cp -p -r "${INDIR}/cfg"  "${OUTDIR}"/ \
    && install -m 0644 "$tmpfile" "${OUTDIR}/rootified-list.txt" \
    && { [ $ON_DIDAQ -eq 0 ] && [ -f "${INDIR}/bias_scan.dat.gz" ] && [ ${#calibration_file[@]} -ne 1 ] \
    && echo "Doing Voltage calibration" \
    && python3 "${SCRIPT_DIR}/convert_bias_scan_to_calibration.py" \
            "${INDIR}/bias_scan.dat.gz" --pedestal_file "${OUTDIR}/pedestal.root" \
            --destination_folder "${OUTDIR}" &>> "${OUTDIR}/voltage_calibration.log" \
    || true; } \
    && echo "Create Monitoring data" \
    && python3 "${SCRIPT_DIR}/mon_write.py" "${OUTDIR}" &>> "${OUTDIR}/monitoring.log" \
    && echo "Conversion complete!"

  exit 1

fi

exit 0
