#! /bin/bash 

INGRESS=/data/ingress/
ARCHIVED=/data/archived/
ROOTIFIED=/data/rootified/
OUTBOX=/data/outbox 
STAGING=/data/staging
TRASH=/data/staging/trash
FRAC=0.05
STATIONS="21 11 22"


#TODO, make this work in parallel

for st in ${STATIONS} ; do 
  echo "STATION $st" 
  for run in $INGRESS/station${st}/run* ; do
    brun=`basename $run`
    echo "RUN  $brun" 
    rootdir=${ROOTIFIED}/station${st}/$brun
    rno-g-convert-run $run $rootdir
    updated=$?
    if [ $updated -eq 1 ] ; then 
      echo "COPYING TO STAGING" 
      outdir=${OUTBOX}/station${st}/$brun

      #if the outdir already exists, move out of the outbox, and delete it 
      if [ -d $outdir ] ; then
        echo "RUN EXISTS IN OUTBOX, TRASHING" 
        mkdir -p ${TRASH} 
        mv $outdir ${TRASH} 
        rm -rf ${TRASH}/$brun
      fi 

      stagedir=${STAGING}/station${st}/$brun
      mkdir -p $stagedir
      cp -p $rootdir/headers.root $stagedir
      cp -p $rootdir/daqstatus.root $stagedir
      cp -p $rootdir/pedestal.root $stagedir
      cp -p -r $rootdir/aux $stagedir
      cp -p -r $rootdir/cfg $stagedir
      rno-g-combine $stagedir/combined.root $rootdir/waveforms.root $rootdir/headers.root $rootdir/daqstatus.root $FRAC
      chmod -R 0777 $stagedir
      mv $stagedir $outdir 
    fi
  done
done

# synchronize ingress with archived
rsync -a $INGRESS $ARCHIVED


#eventually we'll delete stuff in ingress  but let's worry about that later when we have the "real" copy scrpit on the stations 








