#! /bin/bash
ROOT_DATA_DIR="/data"

INGRESS="${ROOT_DATA_DIR}/ingress/"
ARCHIVED="${ROOT_DATA_DIR}/archived/"
ROOTIFIED="${ROOT_DATA_DIR}/rootified/"
OUTBOX="${ROOT_DATA_DIR}/outbox"
STAGING="${ROOT_DATA_DIR}/staging"
TRASH="${ROOT_DATA_DIR}/staging/trash"
EVENTLISTS="${ROOT_DATA_DIR}/eventlists"

FRAC=0.0125
STATIONS="23 11 22 12 21 13 24 14"

# Override STATIONS with command line arguments if provided
if [ $# -gt 0 ]; then
  STATIONS="$*"
fi

# Source an environment
if [ -f /rno-g/etc/autoconverter.env ]
then
  source /rno-g/etc/autoconverter.env
fi

echo "Stations to process: $STATIONS"
echo "Fraction: $FRAC"

#TODO, make this work in parallel

# don't expand globs to themselves if no match
shopt -s nullglob

for st in ${STATIONS} ; do
  for run in $INGRESS/station${st}/run* ; do
    brun=$(basename $run)
    echo "Station $st: $brun"
    rootdir=${ROOTIFIED}/station${st}/$brun
    mkdir -p log/$st/$brun

    rno-g-convert-run $run $rootdir &>> log/$st/$brun/convert.log
    updated=$?

    if [ $updated -eq 1 ] ; then
      echo "RUN UPDATED! -- COPYING TO STAGING"
      outdir=${OUTBOX}/station${st}/$brun

      #if the outdir already exists, move out of the outbox, and delete it
      if [ -d $outdir ] ; then
        echo "RUN EXISTS IN OUTBOX, TRASHING"
        mkdir -p ${TRASH}
        mv $outdir ${TRASH}
        rm -rf "${TRASH:?}/$brun"
      fi

      # Create staging directory and copy additional data which will be send south
      # DO NOT COPY aux/ and cfg/ to the $outdir (via $stagedir)!
      # They are copied directly from INGRESS to desy!
      stagedir=${STAGING}/station${st}/$brun
      mkdir -p $stagedir
      cp -p $rootdir/headers.root $stagedir
      cp -p $rootdir/daqstatus.root $stagedir
      cp -p $rootdir/pedestal.root $stagedir
      cp -p $rootdir/runinfo.root $stagedir
      # copy exactly one calibration file if available
      calibration_file=("${rootdir}"/volCalConsts*)
      if [ ${#calibration_file[@]} -eq 1 ]; then
        cp -p "${calibration_file[0]}" $stagedir
      fi

      echo "RUN rno-g-combine"
      rno-g-combine $stagedir/combined.root $rootdir/waveforms.root $rootdir/headers.root \
        $rootdir/daqstatus.root $rootdir/runinfo.root $FRAC &> log/$st/$brun/combine.log

      mkdir -p $EVENTLISTS/station${st}
      rno-g-make-eventlist $stagedir/combined.root > ${EVENTLISTS}/station${st}/run${brun}.list
      chmod -R 0777 $stagedir
      echo "MOVE $brun to OUTBOX"
      mv $stagedir $outdir

    fi
  done
done

# synchronize ingress with archived
rsync -a --exclude=".*" $INGRESS $ARCHIVED
