name: Test install

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.7
      uses: actions/setup-python@v5
      with:
        python-version: 3.7
    - name: Cache pip
      uses: actions/cache@v4
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('mattak/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Test installation (ROOTless)
      run: |
        pip install -v .
    - name: Cache ROOT
      id: cache-root
      uses: actions/cache@v4
      with:
        path: root
        key: ${{ runner.os }}
    - name: Download ROOT
      if: steps.cache-root.outputs.cache-hit != 'true'
      run: |
        wget https://root.cern/download/root_v6.30.04.Linux-ubuntu22.04-x86_64-gcc11.4.tar.gz
        tar -xzvf root_v6.30.04.Linux-ubuntu22.04-x86_64-gcc11.4.tar.gz
    - name: Install ROOT
      run: |
        sudo apt-get install dpkg-dev cmake g++ gcc binutils libx11-dev libxpm-dev libxft-dev libxext-dev python3 libssl-dev libafterimage0
        source root/bin/thisroot.sh
    - name: Test installation (ROOT)
      run:
        pip install -v .
