name: Test install

on:
  push:
  workflow_dispatch:
  schedule: # run once a week on Sunday to prevent benchmark file from being evicted - there may be a better solution
    - cron: '0 0 * * SUN'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Cache pip
      uses: actions/cache@v4
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('mattak/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Cache sample file
      id: cache-sample-file
      uses: actions/cache@v4
      with:
        path: tests/data
        key: test-data
    - name: Download sample file
      if: steps.cache-sample-file.outputs.cache-hit != 'true'
      run: |
        wget https://rnog-data.zeuthen.desy.de/rnog_share/mattak_ci/station23.tar.gz
        mkdir -p tests/data
        tar -xavf station23.tar.gz -C tests/data/
        ls -l tests/data/station23/run1144
    - name: Get previous benchmark results
      uses: actions/cache/restore@v4
      with:
        path: tests/benchmark.json
        key: benchmark-data
    - name: Test installation (ROOTless)
      run: |
        pip install -v .
    - name: Read a sample file (ROOTless)
      run: |
        python3 tests/test_dataset.py --station=0 --run=0 --data_dir=./tests/data/station23/run1144 --backend uproot --benchmark ${{ github.sha }}
    - name: Calibrate a sample file (ROOTless)
      run: |
        python3 tests/test_dataset.py --station=0 --run=0 --data_dir=./tests/data/station23/run1144 --backend uproot --calibrate -vc tests/data/station23/run1144/volCalConsts_pol9_s23_1682353436-1682354903.root --benchmark ${{ github.sha }}
    - name: Read incomplete data from headers (ROOTless)
      run: |
        python3 tests/test_dataset.py --station=0 --run=0 --data_dir=./tests/data/station23/run1144 --backend uproot --no-skip-incomplete --benchmark ${{ github.sha }}
    - name: Cache ROOT
      id: cache-root
      uses: actions/cache@v4
      with:
        path: root_v6.30.04.Linux-ubuntu22.04-x86_64-gcc11.4.tar.gz
        key: ${{ runner.os }}
    - name: Download ROOT
      if: steps.cache-root.outputs.cache-hit != 'true'
      run: |
        wget https://root.cern/download/root_v6.30.04.Linux-ubuntu22.04-x86_64-gcc11.4.tar.gz
    - name: Install ROOT
      run: |
        sudo apt-get install dpkg-dev cmake g++ gcc binutils libx11-dev libxpm-dev libxft-dev libxext-dev python3 libssl-dev libafterimage0
        tar -xzf root_v6.30.04.Linux-ubuntu22.04-x86_64-gcc11.4.tar.gz
        source root/bin/thisroot.sh
    - name: Test installation (ROOT)
      run: |
        source root/bin/thisroot.sh
        pip install -v .
    - name: Read a sample file (ROOT)
      run: |
        source root/bin/thisroot.sh
        python3 tests/test_dataset.py --station=0 --run=0 --data_dir=./tests/data/station23/run1144 --backend pyroot --benchmark ${{ github.sha }}
    - name: Calibrate a sample file
      run: |
        source root/bin/thisroot.sh
        python3 tests/test_dataset.py --station=0 --run=0 --data_dir=./tests/data/station23/run1144 --backend pyroot --calibrate -vc tests/data/station23/run1144/volCalConsts_pol9_s23_1682353436-1682354903.root --benchmark ${{ github.sha }}
    - name: Read incomplete data from headers
      run: |
        source root/bin/thisroot.sh
        python3 tests/test_dataset.py --station=0 --run=0 --data_dir=./tests/data/station23/run1144 --backend pyroot --no-skip-incomplete --benchmark ${{ github.sha }}
    - name: Read a sample file (all)
      run: |
        source root/bin/thisroot.sh
        export RNO_G_DATA="$PWD/tests/data/"
        python3 tests/test_dataset_all.py
    - name: Compare backends
      run: |
        source root/bin/thisroot.sh
        python3 tests/compare_backends.py --station=0 --run=0 --data_dir tests/data/station23/run1144/ -vc tests/data/station23/run1144//volCalConsts_pol9_s23_1682353436-1682354903.root
        python3 tests/compare_backends.py --station=0 --run=0 --data_dir tests/data/station23/run1144/ -vc tests/data/station23/run1144//volCalConsts_pol9_s23_1682353436-1682354903.root --calibrate
    - name: Benchmark against previous results
      run: |
        python3 tests/evaluate_benchmarks.py --benchmark-file tests/benchmark.json ${{ github.sha }}
    - name: Export benchmark results (only on main)
      if: ${{ github.ref == 'refs/heads/main'}}
      uses: actions/cache/save@v4
      with:
        key: benchmark-data
        path: tests/benchmark.json
